% ADVANCED ROBOTICS
% PRACTICE 4: Local navigation with potential fields
% Obstacle avoidance

clc
clearvars
close all

%% Occupancy map loading
map_img = imread('map.png');
map_neg = imcomplement(map_img);
map_bin = imbinarize(map_neg);
occ_map = binaryOccupancyMap(map_bin);
show(occ_map);

% Mark start and goal points
hold on;
title('Select the start and goal points of the robot trajectory');
start_pos = ginput(1);
plot(start_pos(1), start_pos(2), 'go', 'MarkerFaceColor', 'green');  % Draw the start point
goal_pos = ginput(1);
plot(goal_pos(1), goal_pos(2), 'ro', 'MarkerFaceColor', 'red');      % Draw the goal point

% Sensor configuration (scanning laser)
max_range = 10;
angles = -pi/2:(pi/180):pi/2; % Laser sweep angular resolution

% Vehicle characteristics and method parameters
v = 0.4;             % Robot velocity
D = 1.5;             % Range of the obstacle repulsion field effect
alpha = 1;           % Attraction component coefficient
beta = 100;          % Repulsion component coefficient

%% Initialization
robot = [start_pos 0];     % The robot starts at the initial position (zero orientation)
path = [];                 % Stores the traveled path
path = [path; robot];      % Add the current robot position to the path
iteration = 0;             % Control the number of iterations in case of a local minimum

%% Trajectory calculation
while norm(goal_pos - robot(1:2)) > v && iteration < 1000    % Until less than one iteration from the goal (10 cm)
   
    % 1. Simulate LiDAR sensor to obtain local obstacles
    obs = SimulateLidar(robot, occ_map, angles, max_range);
    
    % 2. Calculate the attractive force towards the goal
    attraction_vector = goal_pos - robot(1:2);
    goal_distance = norm(attraction_vector);
    
    % Attractive force towards the goal
    F_atr = alpha * attraction_vector; 
    
    % 3. Calculate the repulsive force generated by obstacles
    F_rep = [0, 0];
    for i = 1:size(obs, 1)
        if ~isnan(obs(i,1)) % Discard laser rays that do not hit anything
            % Vector pointing from the obstacle towards the robot
            obs_vector = robot(1:2) - obs(i,:); 
            obs_distance = norm(obs_vector);
            
            % Repulsion only takes effect if the obstacle is at a distance less than or equal to D
            if obs_distance <= D && obs_distance > 0
                % Calculation of repulsion magnitude and direction
                rep_magnitude = beta * (1/obs_distance - 1/D) * (1/obs_distance^2);
                rep_direction = obs_vector / obs_distance;
                
                % Accumulate the total repulsive force
                F_rep = F_rep + rep_magnitude * rep_direction;
            end
        end
    end
    
    % 4. Calculate the resultant force (Superposition)
    F_res = F_atr + F_rep;
    
    % 5. Update robot kinematics
    res_magnitude = norm(F_res);
    if res_magnitude > 0
        movement_vector = F_res / res_magnitude; % Unit direction vector
    else
        movement_vector = [0, 0]; % Total block state (local minimum)
    end
    
    % The robot advances one step depending on velocity 'v'
    robot(1:2) = robot(1:2) + v * movement_vector;
    
    % Update the robot's orientation in radians towards its movement direction
    robot(3) = atan2(movement_vector(2), movement_vector(1));
   
    path = [path; robot];	% Add the new position to the followed path
    plot(path(:,1), path(:,2), 'r');
    drawnow
    iteration = iteration + 1;
end

if iteration == 1000   % It has fallen into a local minimum
    fprintf('Failed to reach the destination. Trapped in a local minimum.\n')
else
    fprintf('Destination reached successfully.\n')
end

%% Function to simulate the sensor
function [obs] = SimulateLidar(robot, occ_map, angles, max_range)
    obs = rayIntersection(occ_map, robot, angles, max_range);
    
    % plot(obs(:,1), obs(:,2), '*r') % LiDAR intersection points
    % plot(robot(1), robot(2), 'ob') % Robot position
    % for i = 1:length(angles)
    %     plot([robot(1), obs(i,1)],...
    %         [robot(2), obs(i,2)], '-b') % Intersection rays
    % end
    % % plot([robot(1), robot(1)-6*sin(angles(4))],...
    % %     [robot(2), robot(2)+6*cos(angles(4))], '-b') % Out of range rays
end